websocket:
  url: "ws://127.0.0.1:8181"
  reconnect_delay: 5

arbitrage:
  min_profit_pct: 0.3  # Minimum profit after fees and spreads
  max_data_age_sec: 3  # Maximum age of data in seconds

output:
  file: "situations.jsonl"
  console: true
